return {
  ['clang-tidy'] = require('guard-collection.linter.clang-tidy'),
  codespell = require('guard-collection.linter.codespell'),
  detekt = require('guard-collection.linter.detekt'),
  eslint = require('guard-collection.linter.eslint'),
  eslint_d = require('guard-collection.linter.eslint_d'),
  flake8 = require('guard-collection.linter.flake8'),
  golangci_lint = require('guard-collection.linter.golangci_lint'),
  hadolint = require('guard-collection.linter.hadolint'),
  hlint = require('guard-collection.linter.hlint'),
  ktlint = require('guard-collection.linter.ktlint'),
  luacheck = require('guard-collection.linter.luacheck'),
  sqlfluff = require('guard-collection.linter.sqlfluff'),
  pylint = require('guard-collection.linter.pylint'),
  rubocop = require('guard-collection.linter.rubocop'),
  selene = require('guard-collection.linter.selene'),
  shellcheck = require('guard-collection.linter.shellcheck'),
  stylelint = require('guard-collection.linter.stylelint'),
  ruff = require('guard-collection.linter.ruff'),
  typos = require('guard-collection.linter.typos'),
  mypy = require('guard-collection.linter.mypy').mypy,
  mypyc = require('guard-collection.linter.mypy').mypyc,
  dmypy = require('guard-collection.linter.mypy').dmypy,
}
