name: CI

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Stylua
        uses: JohnnyMorganz/stylua-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check .

  test:
    name: Run Test
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Test Setup (Neovim Nightly)
        uses: rhysd/action-setup-vim@v1
        id: vim
        with:
          neovim: true
          version: nightly

      - name: Test Setup (Lua)
        uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "luajit-openresty"

      - name: Test Setup (Luarocks)
        uses: leafo/gh-actions-luarocks@v4

      - name: Package Manager Setup (Python)
        uses: actions/setup-python@v4

      - name: Package Manager Setup (Rust)
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt, cargo

      - name: Package Manager Setup (npm)
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Package Manager Setup (homebrew)
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install Tools
        shell: bash
        run: bash ./test/setup.sh

      - name: Formatter Test
        shell: bash
        run: |
          source ./test/env.sh
          vusted ./test/formatter

      - name: Linter Test
        shell: bash
        if: always()
        run: |
          source ./test/env.sh
          for linter_test in ./test/linter/*_spec.lua; do
              vusted $linter_test
          done
